# Generated by Django 5.2 on 2026-04-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_adminnotification_notification_type"),
    ]

    operations = []
