# Generated by Django 5.2 on 2025-10-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_registration', 'New User Registration'), ('user_approved', 'User Approved'), ('user_rejected', 'User Rejected'), ('user_deleted', 'User Deleted')], max_length=20),
        ),
    ]
