# Generated by Django 5.2 on 2025-10-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tags for the recipe'),
        ),
    ]
