# Generated by Django 5.2.1 on 2025-10-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
