# Generated by Django 5.2.1 on 2025-10-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_recipe_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='protein_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
